 spring:
   datasource:
     url: ${DATASOURCE_URL}
#     url: jdbc:mysql://34.22.86.151:3306/hana_green_world_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
     username: ${DATASOURCE_USERNAME}
     password: ${DATASOURCE_PASSWORD}
#     username: root
#     password: Password123!
     driver-class-name: com.mysql.cj.jdbc.Driver