# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-minutes: 1440  # 24시간
  refresh-token-validity-in-days: 30

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

gemini:
  api:
    key: ${GEMINI_API_KEY}